apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
    run: kuard
    env: dev
spec:
  selector:
    matchLabels:
      run: kuard
  replicas: 2
  template:
    metadata:
      labels:
        run: kuard
    spec:
      containers:
        - name: kuard
          image: docker.io/pheely/kuard:latest
          ports:
            - containerPort: 8080
